dist: xenial
language: generic
sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - zip
script:
- sudo bash ./.travis/create-image
- ls -lh raspbian.img

before_deploy:
  - export TSTAMP=$(date +'%Y%m%d%H%M')
  - mv raspbian.img susibian-$TSTAMP.img
  - zip susibian-$TSTAMP.zip susibian-$TSTAMP.img

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: susibian-*.zip
  skip_cleanup: true
  on:
    tags: true

