dist: xenial
language: generic
sudo: required

services:
  - docker

env:
  - TARGET=debian VERSION=stretch
  - TARGET=debian VERSION=buster
  - TARGET=ubuntu VERSION=18.04
  - TARGET=ubuntu VERSION=19.04

# the default script for docker tests
script:
  - docker run -v ${TRAVIS_BUILD_DIR}:/tmp/installer -w /tmp/installer -it --rm $TARGET:$VERSION sh -c "
      export DEBIAN_FRONTEND=noninteractive ;
      apt-get update ;
      apt-get install -y --no-install-recommends lsb-release git ca-certificates wget sudo ;
      ./install.sh"

jobs:
  include:
    - os: linux
      env:
        - TARGET=raspi
        - VERSION=stretch
      before_install: sudo apt-get update ; sudo apt-get install qemu qemu-user-static binfmt-support parted wget dosfstools zip xz-utils
      script:
        - sudo bash ./.travis/create-image
        - ls -lh raspbian.img

before_deploy:
  - export TSTAMP=$(date +'%Y%m%d%H%M')
  - mv raspbian.img susibian-$TSTAMP.img
  - travis_wait 30 xz --compress --verbose susibian-$TSTAMP.img 2>&1
  - rm susibian-$TSTAMP.img

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: susibian-*.img.xz
  skip_cleanup: true
  on:
    tags: true
    condition: $TARGET = raspi

