dist: xenial
language: generic
sudo: required

services:
  - docker

#
# note, the global variables NEED to be defined like this, because travis-ci is broken
# wrt deep merge of env settings, see
# https://github.com/travis-ci/travis-ci/issues/8655
# https://github.com/travis-ci/docs-travis-ci-com/issues/1485#issuecomment-351726416
env:
  global:
    TRIGGER_BRANCH=""
    TRIGGER_SOURCE=""
  matrix:
    - TARGET=debian VERSION=stretch
    - TARGET=debian VERSION=buster
    - TARGET=ubuntu VERSION=18.04
    - TARGET=ubuntu VERSION=18.10
    - TARGET=ubuntu VERSION=19.04

# the default script for docker tests
# try running installation as user pi instead of root
script:
  - echo "TRIGGER SOURCE = $TRIGGER_SOURCE, TRIGGER BRANCH = $TRIGGER_BRANCH"
  - .travis/run-docker

jobs:
  include:
    - os: linux
      env:
        - TARGET=raspi
        - VERSION=stretch
      before_install: sudo apt-get update ; sudo apt-get install qemu qemu-user-static binfmt-support parted wget dosfstools zip pixz
      script:
        - sudo -E bash ./.travis/create-image
        - ls -lh raspbian.img

before_deploy:
  - export TSTAMP=$(date +'%Y%m%d%H%M')
  - mv raspbian.img susibian-$TSTAMP.img
  - travis_wait 30 pixz susibian-$TSTAMP.img susibian-$TSTAMP.img.xz
  - rm -f susibian-$TSTAMP.img

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: susibian-*.img.xz
  skip_cleanup: true
  on:
    tags: true
    condition: $TARGET = raspi

